name: build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: cmd
      run: git submodule update --init --force --recursive
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: CMake
      run: |
        cd client
        cmake -G "Visual Studio 16 2019" -A x64 -B "build"
    - name: MSBuild
      run: |
        cd client/build
        msbuild autd3.sln /t:build /p:Configuration=Release

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: Build
      run: |
        cd client
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make

  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: Build
      run: |
        cd client
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
