name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: lint
      run: |
        cd client
        mkdir -p build && cd build
        cmake ..
        make cpplint
